services:
  - type: web
    name: nclean-app
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: VITE_GOOGLE_MAPS_API_KEY
        sync: false
